"""create all tables

Revision ID: 7952cf8842e5
Revises: 
Create Date: 2026-05-14 17:19:17.789044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7952cf8842e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('iata_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_index(op.f('ix_airports_country_code'), 'airports', ['country_code'], unique=False)
    op.create_index(op.f('ix_airports_is_major'), 'airports', ['is_major'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('home_airport', sa.String(length=3), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('destinations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_budget_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_created_at'), 'itineraries', ['created_at'], unique=False)
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('target_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_is_active'), 'price_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_price_alerts_last_checked_at'), 'price_alerts', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('distance_km', sa.Integer(), nullable=True),
    sa.Column('avg_duration_min', sa.Integer(), nullable=True),
    sa.Column('avg_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_iata'], ['airports.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_iata'], ['airports.iata_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_iata', 'destination_iata', name='uq_route_origin_destination')
    )
    op.create_index(op.f('ix_routes_origin_iata'), 'routes', ['origin_iata'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('depart_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('passengers', sa.SmallInteger(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('origin_iata', sa.String(length=3), nullable=False),
    sa.Column('destination_iata', sa.String(length=3), nullable=False),
    sa.Column('result_count', sa.SmallInteger(), nullable=True),
    sa.Column('min_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_history_route', 'search_history', ['origin_iata', 'destination_iata'], unique=False)
    op.create_index(op.f('ix_search_history_searched_at'), 'search_history', ['searched_at'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('cabin_class', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_captured_at'), 'price_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_route_id'), 'price_snapshots', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_snapshots_route_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_captured_at'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_searched_at'), table_name='search_history')
    op.drop_index('ix_search_history_route', table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_routes_origin_iata'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_last_checked_at'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_is_active'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_created_at'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_airports_is_major'), table_name='airports')
    op.drop_index(op.f('ix_airports_country_code'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
